install! 'cocoapods', :share_schemes_for_development_pods => true
use_frameworks!
abstract_target 'AppleTransparencyReportPods' do
	pod 'FastMath'
    pod 'Pippin/Extensions'
    
    target 'AppleTransparencyReport'
end
